### ISSUE TITLE
Exception thrown when saving the note

### ISSUE THREAD

**Issue by flutternoob** [smartherd/Flutter-Demos#6]
I keep getting the following exception when I try to save the note to the database:

`E/flutter (18356): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: DatabaseException(table note_table has no column named description (code 1 SQLITE_ERROR[1]): , while compiling: INSERT INTO note_table (title, description, priority, date) VALUES (?, ?, ?, ?)) sql 'INSERT INTO note_table (title, description, priority, date) VALUES (?, ?, ?, ?)' args [frdf, hrdgy, 2, Mar 27, 2020]}`

**Comment by yasharma2301** [comment]
> 
> 
> I keep getting the following exception when I try to save the note to the database:
> 
> `E/flutter (18356): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: DatabaseException(table note_table has no column named description (code 1 SQLITE_ERROR[1]): , while compiling: INSERT INTO note_table (title, description, priority, date) VALUES (?, ?, ?, ?)) sql 'INSERT INTO note_table (title, description, priority, date) VALUES (?, ?, ?, ?)' args [frdf, hrdgy, 2, Mar 27, 2020]}`

Check your SQL query again
